import { MODULES } from './principal';

export const GEN_AUTHORITIES = {
  CODE: MODULES.GENERAL.CODE,
  SEGURIDAD: {
    CODE: MODULES.GENERAL.SUBS.SEGURIDAD,
    ADMINISTRADOR: `${MODULES.GENERAL.SUBS.SEGURIDAD}001`,
    GESTIONAR_USUARIOS: `${MODULES.GENERAL.SUBS.SEGURIDAD}002`,
    GESTIONAR_PERMISOS_ENTIDAD: `${MODULES.GENERAL.SUBS.SEGURIDAD}003`,
    CREAR_PERMISOS: `${MODULES.GENERAL.SUBS.SEGURIDAD}004`,
  },
};

export const ADMIN_AUTHORITY = GEN_AUTHORITIES.SEGURIDAD.ADMINISTRADOR;
